import{a as h,S as v,i as d}from"./assets/vendor-483db976.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const b="https://pixabay.com/api/";async function L(n,t=1){const o={key:"42543975-3eca36a47ffade116cf6655c4",q:n,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:t};try{const{data:s}=await h.get(b,{params:o});return s.hits}catch{return{error:!0}}}function S({title:n,value:t}){return`<li class="flex-col flex-center">
            <span class="bold">${n}</span>
            <span>${t}</span>
        </li>`}function q({webformatURL:n,largeImageURL:t,tags:o,likes:s,views:e,comments:r,downloads:i}){return`
    <a href="${t}"  class="b-1 bc-gray over-hidden r-10">
        <img alt="${o}" src="${n}" class="h-200 w-full" alt="" />
        <ul class="flex-space p-4+20 fs-12" >
            ${[{title:"Likes",value:s},{title:"Views",value:e},{title:"Comments",value:r},{title:"Downloads",value:i}].map(g=>S(g)).join(`
`)}
        </ul>
    </a>`}const p=document.createElement("div");function w(n,t){let o="";for(const r of n)o+=q(r);p.innerHTML=o;let s=[...p.children];t.append(...s);const e=s[0].getBoundingClientRect();scrollBy(0,e.y)}const m=document.querySelector("form"),u=document.querySelector("main"),c=document.querySelector("#loader"),a=document.querySelector("#more");let f=1,l="";async function y(n){n.preventDefault();const t=m.elements.image;if(t.value.trim()&&(l=t.value.trim()),!l)return;c.style.display="",a.style.display="none";const o=await L(l,f);if(o.error)return l="",c.style.display="none",a.style.display="none",d.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});if(c.style.display="none",a.style.display="",t.value="",o.length==0)return a.style.display="none",u.innerHTML="",d.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});w(o,u),x.refresh(),f++}const x=new v("main a",{captionsData:"alt",captionDelay:250});m.addEventListener("submit",n=>{u.innerHTML="",f=1,y(n)});a.addEventListener("click",y);
//# sourceMappingURL=commonHelpers.js.map
