import{a as h,i as d,S as v}from"./assets/vendor-483db976.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const b="https://pixabay.com/api/";async function L(o,t=1){const n={key:"42543975-3eca36a47ffade116cf6655c4",q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:t};try{const{data:s}=await h.get(b,{params:n});return s.hits}catch{return{error:!0}}}function w({title:o,value:t}){return`<li class="flex-col flex-center">
            <span class="bold">${o}</span>
            <span>${t}</span>
        </li>`}function S({webformatURL:o,largeImageURL:t,tags:n,likes:s,views:e,comments:r,downloads:i}){return`
    <a href="${t}"  class="b-1 bc-gray over-hidden r-10">
        <img alt="${n}" src="${o}" class="h-200 w-full" alt="" />
        <ul class="flex-space p-4+20 fs-12" >
            ${[{title:"Likes",value:s},{title:"Views",value:e},{title:"Comments",value:r},{title:"Downloads",value:i}].map(g=>w(g)).join(`
`)}
        </ul>
    </a>`}const m=document.createElement("div");function x(o,t){let n="";for(const r of o)n+=S(r);m.innerHTML=n;let s=[...m.children];t.append(...s);const e=s[0].getBoundingClientRect();scrollBy(0,e.y)}const p=document.querySelector("form"),u=document.querySelector("main"),c=document.querySelector("#loader"),a=document.querySelector("#more");let f=1,l="";async function y(o){o.preventDefault();const t=p.elements.image;if(t.value.trim()&&(l=t.value.trim()),!l)return;c.style.display="",a.style.display="none";const n=await L(l,f);if(n.error)return l="",c.style.display="none",a.style.display="none",d.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});if(await new Promise(e=>setTimeout(()=>e(),2e3)),c.style.display="none",a.style.display="",t.value="",n.length==0)return a.style.display="none",u.innerHTML="",d.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});x(n,u),new v("main a",{captionsData:"alt",captionDelay:250}).refresh(),f++}p.addEventListener("submit",o=>{u.innerHTML="",f=1,y(o)});a.addEventListener("click",y);
//# sourceMappingURL=commonHelpers.js.map
